In [2]:
import numpy as np

### 1. Eliminacja Gaussa-Jordana

In [3]:
import random
x=np.array([[6,1,4,12,1,4],[4,4,2,3,5,4],[1,1,1,7,1,6],[1,1,9,1,3,7],[1,1,5,3,17,2]], dtype=float)

print(x)
for i in range(0,len(x)):
    x[i][:]=(x[i][:])/x[i][i]
    
    for j in range(0,len(x)):
        if i!=j:            
            t=x[i][:]*x[j][i]
            x[j][:]=x[j][:]-t
            t=x[i][:]*x[j][i]
            x[j][:]=x[j][:]-t
    print(x.round(3)) 
    print()

[[ 6.  1.  4. 12.  1.  4.]
 [ 4.  4.  2.  3.  5.  4.]
 [ 1.  1.  1.  7.  1.  6.]
 [ 1.  1.  9.  1.  3.  7.]
 [ 1.  1.  5.  3. 17.  2.]]
[[ 1.     0.167  0.667  2.     0.167  0.667]
 [ 0.     3.333 -0.667 -5.     4.333  1.333]
 [ 0.     0.833  0.333  5.     0.833  5.333]
 [ 0.     0.833  8.333 -1.     2.833  6.333]
 [ 0.     0.833  4.333  1.    16.833  1.333]]

[[ 1.    0.    0.7   2.25 -0.05  0.6 ]
 [ 0.    1.   -0.2  -1.5   1.3   0.4 ]
 [ 0.    0.    0.5   6.25 -0.25  5.  ]
 [ 0.    0.    8.5   0.25  1.75  6.  ]
 [ 0.    0.    4.5   2.25 15.75  1.  ]]

[[   1.     0.     0.    -6.5    0.3   -6.4]
 [   0.     1.     0.     1.     1.2    2.4]
 [   0.     0.     1.    12.5   -0.5   10. ]
 [   0.     0.     0.  -106.     6.   -79. ]
 [   0.     0.     0.   -54.    18.   -44. ]]

[[ 1.     0.     0.     0.    -0.068 -1.556]
 [ 0.     1.     0.     0.     1.257  1.655]
 [ 0.     0.     1.     0.     0.208  0.684]
 [-0.    -0.    -0.     1.    -0.057  0.745]
 [ 0.     0.     0.     0.    14.

### 2. Eliminacja Gaussa

In [4]:
x=np.array([[6,1,4,12,1,4],[4,4,2,3,5,4],[1,1,1,7,1,6],[1,1,9,1,3,7],[1,1,5,3,17,2]], dtype=float)
print("Dane wejściowe: \n",x)
print()

# Obliczenie macierzy trójkątnej:
for i in range(0,len(x)):
    
    for j in range(0,len(x)):
        
        if i<j:            
            t=x[i][:]*x[j][i]/x[i][i]
            x[j][:]=x[j][:]-t
            t=x[i][:]*x[j][i]
            x[j][:]=x[j][:]-t

print("Macierz trójkątna: \n",x.round(3))
print()

# Wyznaczenie rozwiązań:
w=np.zeros(5)
b=x[:,5]
w[4]=b[4]/x[len(x)-1][4]

for i in range(3,-1,-1):
    
    s=0
    for j in range(i+1,len(x)):
        s+=w[j]*x[i][j]    
        
    w[i]=(b[i]-s)/x[i][i]
    
print("Rozwiązania: \n", w)

Dane wejściowe: 
 [[ 6.  1.  4. 12.  1.  4.]
 [ 4.  4.  2.  3.  5.  4.]
 [ 1.  1.  1.  7.  1.  6.]
 [ 1.  1.  9.  1.  3.  7.]
 [ 1.  1.  5.  3. 17.  2.]]

Macierz trójkątna: 
 [[   6.       1.       4.      12.       1.       4.   ]
 [   0.       3.333   -0.667   -5.       4.333    1.333]
 [   0.       0.       0.5      6.25    -0.25     5.   ]
 [   0.       0.       0.    -106.       6.     -79.   ]
 [   0.       0.       0.       0.      14.943   -3.755]]

Rozwiązania: 
 [-1.57272727  1.97045455  0.73611111  0.73106061 -0.25126263]


### 3. Dekompozycja LU

$$\left[ \begin{matrix}a_{11}&a_{12}&a_{13}\\ a_{21}&a_{22}&a_{23}\\ a_{31}&a_{32}&a_{33}\\ \end{matrix} \right]  =\left[ \begin{matrix}1&0&0\\ l_{21}&1&0\\ l_{31}&l_{32}&1\\ \end{matrix} \right]  \cdot \left[ \begin{matrix}u_{11}&u_{12}&u_{13}\\ 0&u_{22}&u_{23}\\ 0&0&u_{33}\\ \end{matrix} \right]  $$


$$u_{ij}=a_{ij}-\sum^{i-1}_{k=1} l_{ik}u_{kj},\  i\eqslantless j\  \  \  \  \  \  \  \  \  l_{ij}=\frac{1}{u_{ij}} (a_{ij}-\sum^{j-1}_{k=1} l_{ik}u_{kj}),\  j\  <i\  {}$$

### 4. Metoda Jacobiego (iteracyjna)

In [171]:
def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = np.diag(A)
    R = A - np.diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - np.dot(R,x)) / D
    return x

A = np.array([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
guess = np.array([1.0,1.0])

sol = jacobi(A,b,N=25,x=guess)

print(sol)

[ 7.11110202 -3.22220342]
